name: UXpert
favicon: null
layout_spectrum: 0.5567192411981523
typography_spectrum: 0.7342023586388677
title: User Expert
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6330189483705908
  lightness: 0.3878719846252352
  saturation: 0.34691759827546775
  rhythmicContrast: 0.8682196720037609
purpose: []
